(** Program parsing from JSON

    This module parses JSON strings into programs (values using types in the
    [!module:Lang] module).

    The JSON is assumed to have been generated by [elm-format --json]. *)

open Lang

(** [definitions s] parses a string [s] as a list of datatype, type, and
    expression definitions. *)
val definitions : string -> datatype_env * typ_env * env

(** [exp s] parses a string [s] as an expression. *)
val exp : string -> exp

(** [typ s] parses a string [s] as a type. *)
val typ : string -> typ
