(** Program parsing from JSON

    This module parses JSON strings into programs (values using types in the
    [!module:Lang] module) and throws the [ParseFail] exception upon failure.

    The JSON is assumed to have been generated by [elm-format --json] using
    v0.8.7 of [elm-format]. *)

open Lang

exception ParseFail of string

(** [definitions s] parses a string [s] as a list of datatype, type, and
    expression definitions. *)
val definitions : string -> datatype_env * typ_env * env

(** [variable_definitions s] parses a string [s] as variable definition. *)
val variable_definition : string -> string * typ_scheme * exp

(** [exp s] parses a string [s] as an expression. *)
val exp : string -> exp

(** [typ s] parses a string [s] as a type. *)
val typ : string -> typ
